let num1 = Math.floor(5/4);
let num2 = 5/4;
let x = 1;
let y = 2;
let bool1 = (x == y);
let bool2 = (x != y);
let bool3 = (x > y);
let bool4 = (x < y);
let bool5 = (x >= y);
let bool6 = (x <= y);
let bool7 = (x === y);
let bool8 = (x !== y);
console.log(bool1);
console.log(bool2);
console.log(bool3);
console.log(bool4);
console.log(bool5);
console.log(bool6);
console.log(bool7);
console.log(bool8);
console.log(num1);
console.log(num2);
